### REGISTER
POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "firstName":"Diana",
    "lastName":"Ordoñez",
    "userName":"nana",
    "password":"qwerty",
    "email":"nana@gmail.com"
}


### LOGIN
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "userName":"je34429",
    "password":"qwerty"
}


### REFRESH TOKEN replace <refreshToken> with actual refreshToken from login or refresh token routes response
POST http://localhost:3000/api/auth/refresh-token
content-type: application/json

{
    "refreshToken":"<refreshToken>"
}

### REQUEST QR from 2FA
GET http://localhost:3000/api/auth/2fa/generate
content-type: application/json
Authorization: Bearer <Token>

### VALIDATE 2FA
POST http://localhost:3000/api/auth/2fa/validate
content-type: application/json
Authorization: Bearer <Token>

{
    "totp":"<totp>"
}

### LOGIN 2FA
POST http://localhost:3000/api/auth/2fa/login
content-type: application/json

{
    "tempToken":"<temp-token>",
    "totp":"<totp>"
}

### LOGOUT replace <token> with valid token from login or refresh token routes response
GET http://localhost:3000/api/auth/logout
content-type: application/json
Authorization: Bearer <token>


### LIST USERS (PROTECTED) replace <token> with actual token from login
GET http://localhost:3000/api/users
content-type: application/json
Authorization: Bearer <token>

